language: haskell
before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-none-eabi
  - git clone https://github.com/galoisinc/ivory
  - export IVORY_REPO=$PWD/ivory
  - git clone https://github.com/galoisinc/tower
  - export TOWER_REPO=$PWD/tower
  - git clone https://github.com/galoisinc/ivory-tower-stm32
  - export BSP_REPO=$PWD/ivory-tower-stm32
install:
  - cabal install cabal-install
  - cabal install alex
  - cabal install happy
script:
  - ghc --version
  - cabal --version
  - arm-none-eabi-gcc --version
  - IVORY_REPO=$IVORY_REPO TOWER_REPO=$TOWER_REPO BSP_REPO=$BSP_REPO make create-sandbox
  - IVORY_REPO=$IVORY_REPO TOWER_REPO=$TOWER_REPO BSP_REPO=$BSP_REPO make
  - IVORY_REPO=$IVORY_REPO TOWER_REPO=$TOWER_REPO BSP_REPO=$BSP_REPO make test
ghc:
  - 7.8
