sudo: false
language: haskell
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.22
      - alex-3.1.4
      - happy-1.19.5
      - lib32ncurses5
before_install:
- mkdir -p gcc-arm-embedded
- wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2 -O- | tar xjf - -C gcc-arm-embedded
- export PATH="$(echo $PWD/gcc-arm-embedded/*/bin):/opt/cabal/1.22/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH"
- arm-none-eabi-gcc --version && cabal --version && alex --version && happy --version
install:
- git clone https://github.com/galoisinc/ivory
- export IVORY_REPO=$PWD/ivory
- git clone https://github.com/galoisinc/tower
- export TOWER_REPO=$PWD/tower
- git clone https://github.com/galoisinc/ivory-tower-stm32
- export BSP_REPO=$PWD/ivory-tower-stm32
- git clone https://github.com/aisamanra/s-cargot
- export SCARGOT_REPO=$PWD/s-cargot
script:
- make create-sandbox
- make
- make $ENV_TEST_TARGET
ghc:
- 7.8
branches:
  except:
  - /^wip.*$/
env:
- ENV_TEST_TARGET=haskell-backend-test
- ENV_TEST_TARGET=rpc-backend-test
- ENV_TEST_TARGET=ivory-backend-test
- ENV_TEST_TARGET=tower-backend-test
notifications:
  slack:
    secure: C3wT9S1Hv9sM/HHl8R7nej/Eb2xnSNTfQm1wpoW0zYqdnEMF7Dfy4taw1+PrE+oWaj8TD6HKSwpX7i+73hZNQkZzd3EjrNLOdnwcpfy0bAGs4mPHxkOUvqTP2Rm58pE8jj5q90Kd+L7R6RRDFC7js9CpsJ89F2QG/9HA06VN86Q=
