language: haskell


before_install:
  - git clone https://github.com/galoisinc/ivory
  - export IVORY_REPO=$PWD/ivory
install:
  - cabal install alex
  - cabal install happy
script:
  - IVORY_REPO=$IVORY_REPO make create-sandbox
  - IVORY_REPO=$IVORY_REPO make
  - IVORY_REPO=$IVORY_REPO make test
ghc:
  - 7.8
